project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    background: "#f68c28"
    left:
      - href: index.qmd
        text: Home
      - href: Geo.qmd
        text: Geospatial
        
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy;2024, Harry Gray"
           

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    self-contained: true

editor: visual

